# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoRegressionTestTool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import AutoRegressionTestTool_test
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import time
import os


# 1.增加一个下拉表项，选择对应的测试用例工作表
# 2.增加一个用例循环次数节点
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(1061, 809)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(740, 110, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_chosefile = QtWidgets.QPushButton(Dialog)
        self.pushButton_chosefile.setGeometry(QtCore.QRect(890, 30, 151, 31))
        self.pushButton_chosefile.setObjectName("pushButton_chosefile")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 70, 331, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(60)
        self.splitter.setObjectName("splitter")
        self.pushButton_starttest = QtWidgets.QPushButton(self.splitter)
        self.pushButton_starttest.setObjectName("pushButton_starttest")
        self.pushButton_stoptest = QtWidgets.QPushButton(self.splitter)
        self.pushButton_stoptest.setObjectName("pushButton_stoptest")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 871, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(740, 130, 311, 641))
        self.listWidget.setObjectName("listWidget")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 130, 711, 641))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # 启动测试进程
        self.start_test_thread = start_autotest()
        self.start_test_thread_run = AutoRegressionTestTool_test.running_log_x()

        # 按键功能
        self.pushButton_chosefile.clicked.connect(self.chose_file)
        self.pushButton_starttest.clicked.connect(self.start_test)
        self.pushButton_stoptest.clicked.connect(self.stop_test)
        self.start_test_thread.sinOut.connect(self.test_case_step_list)
        self.start_test_thread_run.running.connect(self.running_log)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AutoRegressionTestTool"))
        self.label.setText(_translate("Dialog", "Running Log"))
        self.label_2.setText(_translate("Dialog", "Test Status"))
        self.label_3.setText(_translate("Dialog", "Chose Test file"))
        self.pushButton_chosefile.setText(_translate("Dialog", "Chose Test file"))
        self.pushButton_starttest.setText(_translate("Dialog", "Start Test"))
        self.pushButton_stoptest.setText(_translate("Dialog", "Stop Test"))

    def chose_file(self, Filepath):
        title = "选择测试用例表格"  # 对话框标题
        file = QtWidgets.QFileDialog.getOpenFileName(caption=title)[0]
        self.lineEdit.setText(file)

    def start_test(self):
        self.pushButton_starttest.setEnabled(False)
        self.pushButton_chosefile.setEnabled(False)
        self.textBrowser.clear()
        self.listWidget.clear()
        self.start_test_thread.start()
        self.start_test_thread_run.start()
        # datatime = time.strftime("%Y-%m-%d %H-%M-%S", time.localtime())
        # test = AutoRegressionTestTool_test.TestPerform(self.lineEdit.text())
        # file = os.path.basename(self.lineEdit.text()).split('.')[0] + datatime
        # test.case_run()

    def test_case_step_list(self,strs):
        self.listWidget.addItem(strs)
        self.listWidget.addItem(self.lineEdit.text())
        self.listWidget.scrollToBottom()

    def running_log(self,msg):
        self.textBrowser.append(msg)

    def stop_test(self):
        self.pushButton_starttest.setEnabled(True)
        self.pushButton_chosefile.setEnabled(True)


class start_autotest(QThread):
    sinOut = pyqtSignal(str)
    def __init__(self, parent=None):
        super(start_autotest, self).__init__(parent)
        # 设置工作状态与初始num数值
        self.working = True
        self.num = 0

    def __del__(self):
        # 线程状态改变与线程终止
        self.working = False
        self.wait()

    def run(self):
        while self.working:
            # 获取文本
            file_str = 'File index{0}'.format(self.num)
            self.num += 1
            # 发射信号
            self.sinOut.emit(file_str)
            self.sleep(1)




